# Generated by Django 5.0.11 on 2025-02-05 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created_date']},
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='datetime',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='group',
            new_name='group_id',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='related_users',
            new_name='related_users_ids',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='transaction',
            new_name='transaction_id',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('added_transaction', 'Added a Transaction'), ('added_you_as_friend', 'Added you as a Friend'), ('added_to_group', 'Added to Group'), ('modified_transaction', 'Modified a Transaction'), ('deleted_transaction', 'Deleted a Transaction'), ('settled_amount', 'Settled the Amount')], max_length=50),
        ),
    ]
