# Generated by Django 5.0.12 on 2025-02-07 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_alter_activity_activity_type'),
        ('group', '0001_initial'),
        ('transaction', '0006_transactionparticipant_is_transaction_sattled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.group'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='transaction_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.transaction'),
        ),
    ]
