# Generated by Django 5.0.8 on 2024-09-26 17:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances_as_user', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances_as_friend', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_transaction_date'],
                'unique_together': {('initiator', 'participant')},
            },
        ),
    ]
