# Generated by Django 5.0.11 on 2025-02-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_transaction_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionparticipant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
