# Generated by Django 5.0.12 on 2025-02-15 06:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_transactionparticipant_is_transaction_sattled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userbalance',
            constraint=models.CheckConstraint(check=models.Q(('initiator', models.F('participant')), _negated=True), name='initiator_not_equal_participant'),
        ),
    ]
