# Generated by Django 5.0.7 on 2024-08-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0002_otp_is_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.CharField(max_length=4, verbose_name='OTP Code'),
        ),
    ]
