# Generated by Django 5.0 on 2023-12-31 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_internal',
            new_name='is_staff',
        ),
    ]
