# Generated by Django 5.0.6 on 2024-07-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0005_alter_user_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invite_token',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['invite_token'], name='core_user_invite__c8818e_idx'),
        ),
    ]
