# Generated by Django 5.0.6 on 2024-07-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_invite_token_user_core_user_invite__c8818e_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='invite_token',
            field=models.CharField(editable=False, max_length=10, null=True, unique=True),
        ),
    ]
