# Generated by Django 5.0.6 on 2024-07-28 08:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_invite_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, help_text='Fiend list of user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='invite_token',
            field=models.CharField(editable=False, help_text='Token to add friend with other users', max_length=10, null=True, unique=True),
        ),
    ]
