# Generated by Django 5.0.6 on 2024-07-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_friends_alter_user_invite_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='invite_token',
            field=models.CharField(help_text='Token to add friend with other users', max_length=10, null=True, unique=True),
        ),
    ]
