# Generated by Django 5.0.8 on 2024-09-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_invite_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='Indicates whether the user has verified their email.', verbose_name='Email Verified'),
        ),
    ]
