# Generated by Django 5.0.8 on 2024-09-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_source',
            field=models.CharField(choices=[('standard', 'Standard'), ('google', 'Google')], default='standard', max_length=10),
        ),
    ]
